version: '3.8'

services:
  dynamodb:
    image: instructure/dynamo-local-admin
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://dynamodb:8000" ]
      interval: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
    depends_on:
      dynamodb:
        condition: service_healthy