name: Demo CI, no CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Checkstyle and SpotBugs
        run: ./gradlew check

      - name: Run Tests
        run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build

      - name: Validate Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Build Docker image
        run: docker build -t health-demo .

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: |
            build/reports/
            build/test-results/
          retention-days: 2

      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: build/libs/
          retention-days: 2